
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: rigel-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/rigel
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: A library for c++ based libraries and rpc libraries

source:
  git_url: ../

outputs:
  - name: rigel-rigel
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      string: "h{{ GIT_DESCRIBE_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('rigel', exact=True) }}
    requirements:
      build:
        - clang # [osx]
        - clangxx #   [osx]
        - gcc =8.5 # [linux]
        - gxx =8.5 # [linux]
        - sysroot_linux-64=2.17 # [linux]
      host:
        - sysroot_linux-64=2.17 # [linux]
      run:
        #- __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}  # [osx and x86_64]
        - sysroot_linux-64=2.17 # [linux]
    test:
      commands:
        - test -f $PREFIX/lib/librigel_rigel.so              # [linux]
        - test -f $PREFIX/lib/librigel_rigel.dylib           # [osx]
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
